add_newline = true

format = """
[┌  $all](bold 208)
"""

[line_break]
# disabled = true

[character]
# disabled = true
vicmd_symbol = "[└ ](bold 208)"
success_symbol = "[└ ](bold 208)"
error_symbol = "[✗ ](bold 208)"

[directory]
# monokai color
# style = "bold 117"
# ayu color
style = "bold 32"
truncation_length = 10
truncate_to_repo = false

[package]
disabled = true
symbol = " "













[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[dart]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

