live_config_reload = true

[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black =	"#383A4A"
blue = 	"#4E9FFF"
cyan = 	"#54FFE8"
green =	"#7AFF6E"
magenta	= "#FF8AE5"
red = 	"#FF5D8F"
white =	"#E0E9FF"
yellow =	"#FFD454"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.primary]
background = "#0A0C0E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[cursor]
vi_mode_style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.8

[font.bold]
family = "InputMonoCompressed Nerd Font"
style = "Bold"

[font.bold_italic]
family = "InputMonoCompressed Nerd Font"
style = "Italic"

[font.italic]
family = "MonoLisa Trial"
style = "Italic"
# family = "FantasqueSansMono Nerd Font Mono"
# style = "Normal"

[font.normal]
family = "InputMonoCompressed Nerd Font"
# family = "MonoLisa Trial"
style = "Italic"
# family = "InputMonoCondensed Nerd Font"
# style = "Italic"
# family = "mononoki"
# family = "Iosevka Term"
# style = ""

[font.offset]
x = 2
y = 9

[[keyboard.bindings]]
chars = "}"
key = "RBracket"
mods = "Control"

[[keyboard.bindings]]
chars = "{"
key = "LBracket"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true

[window.padding]
x = 1
y = 0
