reporting: "on"
startuppopupversion: 1
gui:
   theme:
      selectedLineBgColor:
        - reverse
      selectedRangeBgColor:
        - reverse
      activeBorderColor:
        - red
        - bold
      inactiveBorderColor:
        - black
git:
  paging:
    # -w do not show spaces in diff
    colorArg: always -w
    pager: delta --dark --paging=never --24-bit-color=never
    merging:
      args: "--no-ff"
customCommands:
  - key: "M"
    command: "git mergetool {{ .SelectedFile.Name }}"
    context: "files"
    loadingText: "opening git mergetool"
    subprocess: true
  - key: "O"
    command: "git difftool HEAD {{ .SelectedFile.Name }}"
    context: "files"
    loadingText: "opening git difftool"
    subprocess: true
