reporting: "on"
startuppopupversion: 1
gui:
    showIcons: true
    scrollHeight: 2 # how many lines you scroll by
    scrollPastBottom: true # enable scrolling past the bottom
    sidePanelWidth: 0.222
    mainPanelSplitMode: 'horizontal'
    theme:
      optionsTextColor:
        - blue
      selectedLineBgColor:
        - black
      selectedRangeBgColor:
        - black
      activeBorderColor:
        - red
        - bold
      inactiveBorderColor:
        - black
      defaultFgColor:
        - default
git:
  paging:
    # -w do not show spaces in diff
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --diff-highlight
    merging:
      args: "--no-ff"
customCommands:
  - key: "M"
    command: "git mergetool {{ .SelectedFile.Name }}"
    context: "files"
    loadingText: "opening git mergetool"
    subprocess: true
  - key: "O"
    command: "git difftool HEAD {{ .SelectedFile.Name }}"
    context: "files"
    loadingText: "opening git difftool"
    subprocess: true
